apiVersion: v1
kind: Service
metadata:
  name: wellfed-service
  namespace: wellfed-frontend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # Internal Load Balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: wellfed-deploy